//! feat-api-1: print the kit's public surface, one item per line.
//!
//! Why this exists: a change to the shape of a public item is invisible until
//! a consumer compiles, which is after the release. The four consumers live
//! in their own repositories, so nothing in this one notices. This prints a
//! snapshot that `scripts/check-api.sh` compares against the checked-in
//! `docs/API_SURFACE.txt`, so a shape change has to be acknowledged.
//!
//! Why a source parse and not rustdoc JSON: rustdoc's JSON format moves
//! between nightlies, and this has to keep working offline with the pinned
//! stable toolchain. `syn` parses exactly what the compiler does, so a line
//! here is the real signature — what it cannot do is follow a re-export to
//! where the item is defined, which is why the header says paths are
//! declaration paths.
//!
//! It deliberately does NOT run at a commit (Kenny, 2026-09-10): the gates
//! stay fast, and the release script is where this gate belongs.

use std::path::{Path, PathBuf};

use syn::{Item, ItemEnum, ItemFn, ItemImpl, ItemStruct, ItemTrait, Visibility};

fn main() {
    let root = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "crates/chassis/src".to_string());
    let crate_name = std::env::args()
        .nth(2)
        .unwrap_or_else(|| "chassis".to_string());
    let mut lines = Vec::new();
    walk(Path::new(&root), &crate_name, &mut lines);
    lines.sort();
    lines.dedup();
    println!("# The kit's public surface, as declared (feat-api-1).");
    println!("# Generated by `scripts/check-api.sh`; do not edit by hand.");
    println!("# A line is a declaration path, not a re-export path: an item");
    println!("# re-exported at the crate root appears under the module that");
    println!("# declares it.");
    println!("# items: {}", lines.len());
    for l in lines {
        println!("{l}");
    }
}

fn walk(dir: &Path, module: &str, out: &mut Vec<String>) {
    let mut entries: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let deeper = with_segment(module, &name);
            walk(&path, &deeper, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            let stem = path.file_stem().unwrap().to_string_lossy().to_string();
            let here = match stem.as_str() {
                // `mod.rs` and `lib.rs` are the module itself, not a child.
                "mod" | "lib" => module.to_string(),
                other => with_segment(module, other),
            };
            let text = std::fs::read_to_string(&path).expect("a source file reads");
            let file = syn::parse_file(&text)
                .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));
            items(&file.items, &here, out);
        }
    }
}

fn with_segment(module: &str, seg: &str) -> String {
    if module.is_empty() {
        seg.to_string()
    } else {
        format!("{module}::{seg}")
    }
}

fn items(list: &[Item], module: &str, out: &mut Vec<String>) {
    for item in list {
        match item {
            Item::Fn(ItemFn { vis, sig, .. }) if is_public(vis) => {
                out.push(format!("fn {module}::{}", sig_text(&quote(sig))));
            }
            Item::Struct(ItemStruct {
                attrs,
                vis,
                ident,
                fields,
                ..
            }) if is_public(vis) => {
                // Whether the type is sealed decides how a later addition has
                // to be read: a field added to a sealed struct is additive,
                // the same field on an open one breaks every caller that
                // builds it. Without this the comparison can say a field
                // appeared and nothing more (CF-15, 2026-09-10).
                out.push(format!("struct {module}::{ident}{}", sealed(attrs)));
                for f in fields {
                    if is_public(&f.vis) {
                        let name = f
                            .ident
                            .as_ref()
                            .map(|i| i.to_string())
                            .unwrap_or_else(|| "0".to_string());
                        out.push(format!(
                            "field {module}::{ident}.{name}: {}",
                            sig_text(&quote(&f.ty))
                        ));
                    }
                }
            }
            Item::Enum(ItemEnum {
                attrs,
                vis,
                ident,
                variants,
                ..
            }) if is_public(vis) => {
                // Same reasoning as the struct above: a variant added to a
                // sealed enum is additive, on an open one it breaks every
                // exhaustive `match` a consumer wrote.
                out.push(format!("enum {module}::{ident}{}", sealed(attrs)));
                for v in variants {
                    out.push(format!("variant {module}::{ident}::{}", v.ident));
                }
            }
            Item::Trait(ItemTrait { vis, ident, .. }) if is_public(vis) => {
                out.push(format!("trait {module}::{ident}"));
            }
            Item::Type(t) if is_public(&t.vis) => {
                out.push(format!("type {module}::{}", t.ident));
            }
            Item::Const(c) if is_public(&c.vis) => {
                out.push(format!(
                    "const {module}::{}: {}",
                    c.ident,
                    sig_text(&quote(&c.ty))
                ));
            }
            Item::Impl(ItemImpl {
                self_ty,
                items: inner,
                trait_,
                ..
            }) => {
                // Only inherent impls: a trait impl's methods are the trait's
                // shape, and the trait is already listed.
                if trait_.is_some() {
                    continue;
                }
                let ty = sig_text(&quote(self_ty));
                for i in inner {
                    if let syn::ImplItem::Fn(f) = i
                        && is_public(&f.vis)
                    {
                        out.push(format!("fn {module}::{ty}::{}", sig_text(&quote(&f.sig))));
                    }
                }
            }
            // An inline `mod tests` is private; only a public inline module
            // contributes surface.
            Item::Mod(m) if is_public(&m.vis) => {
                if let Some((_, inner)) = &m.content {
                    let deeper = with_segment(module, &m.ident.to_string());
                    items(inner, &deeper, out);
                }
            }
            _ => {}
        }
    }
}

/// ` [sealed]` when the item carries `#[non_exhaustive]`, empty otherwise.
/// A sealed type can gain a field or a variant without breaking a caller,
/// which is the whole difference between an additive release and a major.
fn sealed(attrs: &[syn::Attribute]) -> &'static str {
    if attrs.iter().any(|a| a.path().is_ident("non_exhaustive")) {
        " [sealed]"
    } else {
        ""
    }
}

fn is_public(vis: &Visibility) -> bool {
    matches!(vis, Visibility::Public(_))
}

fn quote<T: quote::ToTokens>(t: &T) -> String {
    let mut s = proc_macro2::TokenStream::new();
    t.to_tokens(&mut s);
    s.to_string()
}

/// One line, stable spacing: the token stream's own spacing varies with the
/// source, and a snapshot that moves when formatting moves is noise.
fn sig_text(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut last_space = false;
    for ch in s.chars() {
        let space = ch.is_whitespace();
        if space {
            if !last_space {
                out.push(' ');
            }
        } else {
            out.push(ch);
        }
        last_space = space;
    }
    out.replace(" ,", ",")
        .replace(" ;", ";")
        .replace("( ", "(")
        .replace(" )", ")")
        .replace(" <", "<")
        .replace("< ", "<")
        .replace(" >", ">")
        .trim()
        .to_string()
}
